<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <title>PDF Rekap Parkir</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; margin: 25px; }
        h1, h2 { margin: 0; }
        .header { text-align: center; margin-bottom: 20px; }
        .meta { margin-bottom: 15px; }
        .meta div { margin-bottom: 3px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 15px; }
        th, td { border: 1px solid #333; padding: 5px; text-align: left; }
        th { background: #f3f4f6; }
        .right { text-align: right; }
        .footer { margin-top: 10px; font-size: 11px; text-align: right; }
    </style>
</head>
<body>
    <div class="header">
        <h1>PARQEER - Rekap Parkir</h1>
        <p>{{ ucfirst($mode) }} laporan ({{ $date ?? $from }} @if($mode === 'range') s/d {{ $to }} @endif)</p>
    </div>

    <div class="meta">
        <div>Tanggal Cetak: {{ now()->format('d/m/Y H:i') }}</div>
    </div>

    <h2>Ringkasan Per Hari</h2>
    <table>
        <thead>
            <tr>
                <th>Tanggal</th>
                <th class="right">Jumlah Transaksi</th>
                <th class="right">Total (Rp)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($dailyData as $item)
                <tr>
                    <td>{{ $item->date }}</td>
                    <td class="right">{{ $item->count }}</td>
                    <td class="right">{{ number_format($item->total, 0, ',', '.') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <h2>Detail Transaksi</h2>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Plat</th>
                <th>Area</th>
                <th class="right">Jumlah</th>
                <th>Waktu Keluar</th>
            </tr>
        </thead>
        <tbody>
            @foreach($transactions as $tx)
                <tr>
                    <td>{{ $tx->id }}</td>
                    <td>{{ strtoupper($tx->plate_number) }}</td>
                    <td>{{ $tx->area->name ?? '-' }}</td>
                    <td class="right">{{ number_format($tx->amount, 0, ',', '.') }}</td>
                    <td>{{ $tx->exit_time->format('d/m/Y H:i') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">Generated by PARQEER {{ now()->format('d/m/Y H:i') }}</div>
</body>
</html>